javac -cp .:../lib/* GetDate.java
javac -cp .:../lib/* GetBlob.java
javac -cp .:../lib/* ConvertZB.java
javac -cp .:../lib/* ParseFuture.java
javac -cp .:../lib/* DeleteRecords.java
javac -cp .:../lib/* GetPage.java
javac -cp .:../lib/* GetMessage.java
javac -cp .:../lib/* InsertFutures.java
javac -cp .:../lib/* InsertSpot.java
javac -cp .:../lib/* SendMessage.java
javac -cp .:../lib/* TestHarness.java
javac -cp .:../lib/* GetICEMessage.java
javac -cp .:../lib/* InsertNotification.java
javac -cp .:../lib/* Execute.java
